force-app/main/default/objects/Partner_Agreement__c/Partner_Agreement__c.object-meta.xml
<CustomObject>
    <label>Partner Agreement</label>
    <nameField>
        <displayFormat>PA-{MM}-{YYYY}-{000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Agreement__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Harbor Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Premier Harbor Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Premier Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Premier Tumblers</fullName>
            </value>
            <value>
                <fullName>Reusable CamLids and Store Racks</fullName>
            </value>
            <value>
                <fullName>Tumblers</fullName>
            </value>
            <value>
                <fullName>Vizient Harbor Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Vizient Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Vizient Tumblers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/Partner_Agreement_Product__c.object-meta.xml
<CustomObject>
    <label>Partner Agreement Product</label>
    <nameField>
        <displayFormat>PAP-{00000}</displayFormat>
        <label>Partner Agreement Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Agreement Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Approx_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Approx_Capacity__c</fullName>
    <label>Approx Capacity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Case_Pack__c</fullName>
    <label>Case Pack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Disposable_Lid_Code__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Lid_Code__c</fullName>
    <label>Disposable Lid Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Fits_Shoreline_Products__c.field-meta.xml
<CustomField>
    <fullName>Fits_Shoreline_Products__c</fullName>
    <label>Fits Shoreline Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Full_Size_Camrack__c.field-meta.xml
<CustomField>
    <fullName>Full_Size_Camrack__c</fullName>
    <label>Full Size Camrack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Image_Location__c.field-meta.xml
<CustomField>
    <fullName>Image_Location__c</fullName>
    <label>Image Location</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Other_Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Other_Case_Pack__c</fullName>
    <label>Other Case Pack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Outside_Diameter__c.field-meta.xml
<CustomField>
    <fullName>Outside_Diameter__c</fullName>
    <label>Outside Diameter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Product__c/fields/Partner_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Partner_Agreement__c</fullName>
    <label>Partner Agreement</label>
    <referenceTo>Partner_Agreement__c</referenceTo>
    <relationshipLabel>Partner Agreement Products</relationshipLabel>
    <relationshipName>Partner_Agreement_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/Partner_Agreement_Products__mdt.object-meta.xml
<CustomObject>
    <label>Partner Agreement Product</label>
    <pluralLabel>Partner Agreement Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Type of agreements. NOTE THIS NEEDS TO STAY IN SYNC with Partner Agreement picklist Agreement Type! /lightning/setup/ObjectManager/01IF0000002m6dN/FieldsAndRelationships/00NF000000DIUO0/view</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Harbor Mugs &amp; Bowls</fullName>
                <default>true</default>
                <label>Harbor Mugs &amp; Bowls</label>
            </value>
            <value>
                <fullName>Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Premier Harbor Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Premier Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Premier Tumblers</fullName>
            </value>
            <value>
                <fullName>Reusable CamLids and Store Racks</fullName>
            </value>
            <value>
                <fullName>Tumblers</fullName>
            </value>
            <value>
                <fullName>Vizient Harbor Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Vizient Mugs &amp; Bowls</fullName>
            </value>
            <value>
                <fullName>Vizient Tumblers</fullName>
            </value>
            <value>
                <fullName>TestData</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Approx_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Approx_Capacity__c</fullName>
    <label>Approx Capacity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Case_Pack__c</fullName>
    <label>Case Pack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Product Code</description>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Disposable_Lid_Code__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Lid_Code__c</fullName>
    <label>Disposable Lid Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Fits_Shoreline_Products__c.field-meta.xml
<CustomField>
    <fullName>Fits_Shoreline_Products__c</fullName>
    <label>Fits Shoreline Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Full_Size_Camrack__c.field-meta.xml
<CustomField>
    <fullName>Full_Size_Camrack__c</fullName>
    <label>Full Size Camrack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Image_Location__c.field-meta.xml
<CustomField>
    <fullName>Image_Location__c</fullName>
    <description>Images need to be public available. For example, in Documents (classic only)</description>
    <label>Image Location</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Other_Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Other_Case_Pack__c</fullName>
    <label>Other Case Pack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Outside_Diameter__c.field-meta.xml
<CustomField>
    <fullName>Outside_Diameter__c</fullName>
    <label>Outside Diameter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement_Products__mdt/fields/Reusable_Lid_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Reusable_Lid_Capacity__c</fullName>
    <label>Reusable Lid Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaLwc_Util.cls
public with sharing class PaLwc_Util {

    @AuraEnabled(cacheable=true) 
    public static list<Partner_Agreement_Product__c> FindPaProds(id partnerAgreementId){
        //method runs if all I do is a soql. It fails if I do DML after removing cachable=true. 
        //base on debug log looks like the method isn't called
        system.debug('grabbing products');
        list<Partner_Agreement_Product__c> lProds = new list<Partner_Agreement_Product__c>();
        //Hard code a record URL so I can really get the damn thing working
        // string paid = 'a023i0000038GJvAAM';
        /*
        //temporary PA just to get this damn thing working
        Partner_agreement__c PA = new Partner_agreement__c (
            Agreement_Type__c = 'The Wizard News'
        );
        insert PA;       
        paid = pa.id;         
        system.debug('PaID: ' + PA.id);
         
         */
        
        
        
        //Soql Existing record because the above wasn't working. 
        lProds = [select code__c, description__c, id, Image_Location__c, Quantity__c from Partner_Agreement_Product__c where Partner_Agreement__c = :partnerAgreementId];
        system.debug('prods size: ' + lProds.size());
        system.debug('#### ' + lprods);
        system.debug('### ' + partnerAgreementId);
        return lprods;
    }
    
    @AuraEnabled
    public static void createDefaultRows(id partnerAgreementId){
        list<Partner_Agreement_Products__mdt> lProdsMDT =[SELECT Agreement_Type__c,Approx_Capacity__c,Case_Pack__c,Code__c,Description__c,
            DeveloperName,Disposable_Lid_Code__c,Full_Size_Camrack__c,Height__c,Id,
            Image_Location__c,MasterLabel,Other_Case_Pack__c,Outside_Diameter__c,
            Reusable_Lid_Capacity__c,QualifiedApiName,Fits_Shoreline_Products__c 
            FROM Partner_Agreement_Products__mdt where Agreement_Type__c = 'The Wizard News'];   
        list<Partner_Agreement_Product__c> lProds = new list<Partner_Agreement_Product__c>();
        for(Partner_Agreement_Products__mdt prod : lProdsMDT){
            lProds.add(
                new Partner_Agreement_Product__c(
                    Code__c =prod.Code__c,
                    Description__c =prod.Description__c,
                    Image_Location__c = prod.Image_Location__c,                
                    Quantity__c =0,
                    Partner_Agreement__c = partnerAgreementId
                )
            );            
        }
        insert lProds;
    }
}